name: testing out for the first time

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: python-app
  MY_NAME: dhruv1249

permissions:
  packages: write

jobs:
  push_it:
    runs-on: ubuntu-latest

    steps:
      - name: Pull it first
        uses: actions/Checkout@v4

      - name: Build python
        run: docker build -t ghcr.io/${MY_NAME}/${IMAGE_NAME}:${{ github.sha }} ./python-app

      - name: Login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "{MY_NAME}" --password-stdin

      - name: Push image
        run: |
          docker push \
            ghcr.io/${MY_NAME}/${IMAGE_NAME}:${{ github.sha }}

